"""add pantry item

Revision ID: b70a3b3b2ee3
Revises: a5cd83bbad52
Create Date: 2026-07-26 08:07:02.887979

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b70a3b3b2ee3"
down_revision: str | Sequence[str] | None = "a5cd83bbad52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_item",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column(
            "level", sa.SmallInteger(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column("last_bought_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('Grains & pulses', 'Spices & masalas', 'Vegetables & fruit', 'Dairy & eggs', 'Oils & condiments', 'Snacks & packaged')",
            name=op.f("ck_pantry_item_category_allowed"),
        ),
        sa.CheckConstraint(
            "name_normalized <> ''",
            name=op.f("ck_pantry_item_name_normalized_not_blank"),
        ),
        sa.CheckConstraint(
            "char_length(name) <= 200", name=op.f("ck_pantry_item_name_length")
        ),
        sa.CheckConstraint(
            "char_length(name_normalized) <= 200",
            name=op.f("ck_pantry_item_name_normalized_length"),
        ),
        sa.CheckConstraint(
            "level BETWEEN 0 AND 3", name=op.f("ck_pantry_item_level_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_pantry_item_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pantry_item")),
        sa.UniqueConstraint(
            "user_id", "name_normalized", name="uq_pantry_item_user_name"
        ),
    )
    # ### end Alembic commands ###

    # pantry_item is mutable, so it joins the tables kept current by the
    # shared set_updated_at() trigger function created in the initial
    # revision. Alembic does not model triggers, so this is hand-written.
    op.execute(
        "CREATE TRIGGER trg_pantry_item_updated_at BEFORE UPDATE ON pantry_item "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # The trigger is dropped along with its table; set_updated_at() itself
    # belongs to the initial revision and stays.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pantry_item")
    # ### end Alembic commands ###
