"""initial cue schema

Revision ID: a5cd83bbad52
Revises:
Create Date: 2026-07-15 17:56:15.573987

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5cd83bbad52"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables carrying updated_at, kept current by the shared trigger below. Their
# triggers are dropped automatically when the tables are dropped in downgrade().
_UPDATED_AT_TABLES = ("user", "provider_link", "chat_session", "order")


def upgrade() -> None:
    """Upgrade schema."""
    # Shared updated_at trigger function. Not emitted by autogenerate (Alembic
    # does not model functions/triggers), so it is hand-written here. Created
    # before the triggers that reference it.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
          NEW.updated_at = now();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("firebase_uid", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(display_name) <= 200", name=op.f("ck_user_display_name_length")
        ),
        sa.CheckConstraint(
            "char_length(email) <= 320", name=op.f("ck_user_email_length")
        ),
        sa.CheckConstraint(
            "char_length(firebase_uid) <= 128", name=op.f("ck_user_firebase_uid_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("firebase_uid", name=op.f("uq_user_firebase_uid")),
    )
    op.create_table(
        "chat_session",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("selected_address_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(selected_address_id) <= 100",
            name=op.f("ck_chat_session_selected_address_id_length"),
        ),
        sa.CheckConstraint(
            "char_length(title) <= 200", name=op.f("ck_chat_session_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_chat_session_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_session")),
    )
    op.create_index(
        "ix_chat_session_user_recents",
        "chat_session",
        ["user_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "oauth_transaction",
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("code_verifier_ct", sa.LargeBinary(), nullable=False),
        sa.Column(
            "key_version",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('swiggy')", name=op.f("ck_oauth_transaction_provider_allowed")
        ),
        sa.CheckConstraint(
            "char_length(redirect_uri) <= 2000",
            name=op.f("ck_oauth_transaction_redirect_uri_length"),
        ),
        sa.CheckConstraint(
            "char_length(state) <= 128", name=op.f("ck_oauth_transaction_state_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_oauth_transaction_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("state", name=op.f("pk_oauth_transaction")),
    )
    op.create_index(
        op.f("ix_oauth_transaction_expires_at"),
        "oauth_transaction",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_transaction_user_id"),
        "oauth_transaction",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "provider_link",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("access_token_ct", sa.LargeBinary(), nullable=False),
        sa.Column(
            "key_version",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "linked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('swiggy')", name=op.f("ck_provider_link_provider_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired')",
            name=op.f("ck_provider_link_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(scope) <= 500", name=op.f("ck_provider_link_scope_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_provider_link_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_link")),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_provider_link_user_provider"
        ),
    )
    op.create_table(
        "cart_plan",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("address_id", sa.Text(), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(address_id) <= 100",
            name=op.f("ck_cart_plan_address_id_length"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
            name=op.f("fk_cart_plan_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_plan")),
    )
    op.create_index("ix_cart_plan_session", "cart_plan", ["session_id"], unique=False)
    op.create_index(
        "uq_cart_plan_live",
        "cart_plan",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), server_default=sa.text("'text'"), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'text' AND content IS NOT NULL) OR (kind <> 'text' AND payload IS NOT NULL)",
            name=op.f("ck_chat_message_body"),
        ),
        sa.CheckConstraint(
            "kind IN ('text', 'image', 'checklist', 'cart_ready')",
            name=op.f("ck_chat_message_kind_allowed"),
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name=op.f("ck_chat_message_role_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
            name=op.f("fk_chat_message_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_message")),
    )
    op.create_index(
        "ix_chat_message_session", "chat_message", ["session_id", "id"], unique=False
    )
    op.create_table(
        "cart_plan_item",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("ingredient_name", sa.Text(), nullable=False),
        sa.Column("ingredient_qty", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("ingredient_unit", sa.Text(), nullable=True),
        sa.Column("match_status", sa.Text(), nullable=False),
        sa.Column("spin_id", sa.Text(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("pack_size", sa.Text(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("selection_reason", sa.Text(), nullable=True),
        sa.Column(
            "is_addon", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_status <> 'substituted' OR selection_reason IS NOT NULL",
            name=op.f("ck_cart_plan_item_substitution_reason"),
        ),
        sa.CheckConstraint(
            "match_status = 'unavailable' OR (spin_id IS NOT NULL AND quantity IS NOT NULL AND unit_price IS NOT NULL)",
            name=op.f("ck_cart_plan_item_resolved"),
        ),
        sa.CheckConstraint(
            "match_status IN ('matched', 'substituted', 'unavailable')",
            name=op.f("ck_cart_plan_item_match_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(ingredient_name) <= 200",
            name=op.f("ck_cart_plan_item_ingredient_name_length"),
        ),
        sa.CheckConstraint(
            "char_length(ingredient_unit) <= 20",
            name=op.f("ck_cart_plan_item_ingredient_unit_length"),
        ),
        sa.CheckConstraint(
            "char_length(pack_size) <= 50",
            name=op.f("ck_cart_plan_item_pack_size_length"),
        ),
        sa.CheckConstraint(
            "char_length(product_name) <= 300",
            name=op.f("ck_cart_plan_item_product_name_length"),
        ),
        sa.CheckConstraint(
            "char_length(selection_reason) <= 1000",
            name=op.f("ck_cart_plan_item_selection_reason_length"),
        ),
        sa.CheckConstraint(
            "char_length(spin_id) <= 100", name=op.f("ck_cart_plan_item_spin_id_length")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_cart_plan_item_quantity_positive")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_cart_plan_item_unit_price_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["cart_plan.id"],
            name=op.f("fk_cart_plan_item_plan_id_cart_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_plan_item")),
    )
    op.create_index(
        "ix_cart_plan_item_plan", "cart_plan_item", ["plan_id"], unique=False
    )
    op.create_table(
        "order",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("address_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("swiggy_order_id", sa.Text(), nullable=True),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "checkout_started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'placed' OR (swiggy_order_id IS NOT NULL AND placed_at IS NOT NULL)",
            name=op.f("ck_order_placed_has_id"),
        ),
        sa.CheckConstraint(
            "status IN ('placing', 'placed', 'failed', 'unknown')",
            name=op.f("ck_order_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(address_id) <= 100", name=op.f("ck_order_address_id_length")
        ),
        sa.CheckConstraint(
            "char_length(swiggy_order_id) <= 100",
            name=op.f("ck_order_swiggy_order_id_length"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_order_total_nonneg")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["cart_plan.id"],
            name=op.f("fk_order_plan_id_cart_plan"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
            name=op.f("fk_order_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_order_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
    )
    op.create_index("ix_order_plan", "order", ["plan_id"], unique=False)
    op.create_index("ix_order_session", "order", ["session_id"], unique=False)
    op.create_index(
        "ix_order_user",
        "order",
        ["user_id", sa.literal_column("checkout_started_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_order_one_placing",
        "order",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'placing'"),
    )
    op.create_index(
        "uq_order_swiggy_order_id",
        "order",
        ["swiggy_order_id"],
        unique=True,
        postgresql_where=sa.text("swiggy_order_id IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # Attach the shared updated_at trigger to every mutable table. Table names
    # are quoted: "user" and "order" are reserved words in Postgres.
    for table in _UPDATED_AT_TABLES:
        op.execute(
            f'CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON "{table}" '
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_order_swiggy_order_id",
        table_name="order",
        postgresql_where=sa.text("swiggy_order_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_order_one_placing",
        table_name="order",
        postgresql_where=sa.text("status = 'placing'"),
    )
    op.drop_index("ix_order_user", table_name="order")
    op.drop_index("ix_order_session", table_name="order")
    op.drop_index("ix_order_plan", table_name="order")
    op.drop_table("order")
    op.drop_index("ix_cart_plan_item_plan", table_name="cart_plan_item")
    op.drop_table("cart_plan_item")
    op.drop_index("ix_chat_message_session", table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index(
        "uq_cart_plan_live",
        table_name="cart_plan",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index("ix_cart_plan_session", table_name="cart_plan")
    op.drop_table("cart_plan")
    op.drop_table("provider_link")
    op.drop_index(op.f("ix_oauth_transaction_user_id"), table_name="oauth_transaction")
    op.drop_index(
        op.f("ix_oauth_transaction_expires_at"), table_name="oauth_transaction"
    )
    op.drop_table("oauth_transaction")
    op.drop_index("ix_chat_session_user_recents", table_name="chat_session")
    op.drop_table("chat_session")
    op.drop_table("user")
    # ### end Alembic commands ###

    # Triggers were dropped with their tables above; drop the shared function last.
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
